twitter.config:
  consumer_key: TWITTER_CONSUMER_SECRET
  consumer_secret: TWITTER_CONSUMER_SECRET
  access_token: TWITTER_ACCESS_TOKEN
  access_token_secret: TWITTER_ACCESS_TOKEN_SECRET

aws.config:
  version: latest
  region: eu-west-1
  credentials:
    key: AWS_KEY
    secret: AWS_SECRET

mpwar.miner:
  queue_url: AMAZON_SQS_URL

mongodb.options:
  server: MONGO_URL

mongodbodm.options:
  mongodbodm.proxies_dir: /storage/mongodb/proxies
  mongodbodm.hydrator_dir: /storage/mongodb/hydrator
  mongodbodm.dm.options:
    database: miner
    mappings:
      - type: simple_yml
        namespace: Mpwar\DataMiner
        path: src/DataMiner/Infrastructure/Domain/Document/mappings