engines:
  phpcodesniffer:
    enabled: true
    config:
    	standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,controversial,design,naming,unusedcode"
  duplication:
  	enabled: true
    config:
    	languages:
      - php
ratings:
  paths:
  - src/**
  - "**.php"
exclude_paths:
- "**/vendor/**/*"