addons:
  code_climate:
    repo_token: ffe95eb869b09c857a1d001c8c47e606326dd85385fa81c4013b9c4265222176
language: php
php:
  - '7.1'
sudo: false
dist: trusty
before_install:
  - phpenv config-add resources/php.ini
  - apt-get install php-xml
install:
  - composer install
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - vendor/bin/test-reporter